### ISSUE TITLE
Issues with pyrtma bench

### ISSUE THREAD

**Issue by tjmadonna** [dmw109/pyrtma#1]
pyrtma_bench.py needs to be updated to use the latest pyrtma class names (ex: rtmaClient -> Client). There may be more.

**Comment by jmw182** [comment]
The examples may also need to be updated (e.g. I changed types -> internal_types).

**Comment by jmw182** [comment]
The examples seem to work now. @tjmadonna can this issue be closed?

**Comment by jmw182** [comment]
I updated pyrtma_bench in 9b1b9fc. It mostly works again, but still fails if configured to run with publishers but no subscribers. I'm not sure why subscribers are required to avoid this error:

> Traceback (most recent call last):
  File "pyrtma_bench.py", line 225, in <module>
    msg = mod.read_message(timeout=0.100)
  File "c:\git\pyrtma\pyrtma\client.py", line 233, in read_message
    ), "Did not send all the header to message manager."
AssertionError: Did not send all the header to message manager.

**Comment by jmw182** [comment]
I renamed this issue since the remaining bugs I described on September 29 are unrelated to class names.

**Comment by jmw182** [comment]
Recap from debugging this week and meeting with both Tylers today:
At this point the issue seems to happen with both message managers, and with either pyrtma_bench.py or rtma_bench.exe.
The issue appears to be related to unsynchronized subprocesses. When one publisher process finishes before the others even begin, the main process does not get all of the publisher done signals and hangs. This is more likely to happen when there are no subscribers (as the publisher thread normally waits for all subscribers to be ready prior to their send loops), or when the number of messages per publisher is small (such that the processes can finish very quickly). 

Adding a pause BEFORE sending the publisher done signal can resolve the issue, but a pause AFTER the signal and before disconnecting does NOT resolve the issue.
